### PR TITLE
Added support for `http-interop/http-middleware` 0.5.0

### PR DESCRIPTION
**Pull request by michalbundyra**

### CODE REVIEW

**Comment by harikt** [comment]
@webimpress just a note, when working on this https://github.com/harikt/web.expressive/pull/24 , this job https://travis-ci.org/harikt/web.expressive/jobs/286862184 failed to install the dependencies .

I was wondering why it failed when my local system was running the phpunit tests. 

Looking further I removed composer.lock and vendor folder and installed via `composer install` . In the middle composer asked me the version constraint for `http-interop/http-middleware` . I understood the same will be asked for travis where it would have broken.

Adding to composer.json : https://github.com/harikt/web.expressive/pull/24/commits/2dd2bc36271b00f05b34de1fc2e86b28f091a05b fixed the same.

I am not really sure how composer asked for the version constraint, experienced it for the first time.

**Comment by michalbundyra** [comment]
@harikt 
> I am not really sure how composer asked for the version constraint, experienced it for the first time.

Composer asked for the version constraint because of composer plugin I have wrote: [`webimpress/composer-extra-dependency `](https://github.com/webimpress/composer-extra-dependency). The plugin is required by [`webimpress/http-middleware-compatibility`](https://github.com/webimpress/http-middleware-compatibility) which helps us migrate to the latest version of `http-interop/http-middleware` without BC break. The `http-middleware-compatibility ` package is compatible with all released http-interop middlewares and the final customer __must decide__ what version of http-interop middleware to use. The compatibility package is used with Stratigility 2.1 and will be soon also with expressive (I believe [2.1.0](https://github.com/zendframework/zend-expressive/milestone/30?closed=1), already merged to develop). Current expressive version DOES NOT support `http-interop/http-middleware 0.5.0`
 I was wonder how you were able to require that version in your project. I found out, it was possible because of missing dependency in expressive which is fixed in Expressive [2.0.5](https://github.com/zendframework/zend-expressive/releases/tag/2.0.5). Your repository used then version 2.0.4 which allows to use any version of http-interop middleware (but itself supports only 0.4.1). Before it was used as implicit dependency from Stratigility (version 2.0 explicitly requires version 0.4.1 of http-interop middleware, but version 2.1 allows any because of compatibility package). 
Basically right now you __can't__ use `http-interop/http-middleware` 0.5.0 because expressive does not support it yet, only Stratigility 2.1 does.

When expressive and all other modules will be released the migration process will be simply, just `composer update` will do everything. The plugin will be installed, detects currently installed version of `http-interop/http-middleware` and adds the requirement to the `composer.json` file. It allows you to update to the latest version of http-interop middlewares whenever you want, you just need change version of the library in your composer and update your middlewares (or `composer require http-interop/http-middleware:^0.5.0`).
So now, we need to have _explicit_ dependency on `http-interop/http-middleware` in `composer.json`.

The plugin prompt for the constraint only when there is no http-interop middleware installed and doesn't know what version it should use. As you can see, in this PR we have added to `COMPOSER_ARGS` parameter `--no-plugins` to run builds on travis without prompting. Then `composer.json` is not modified during the build and version matching all requirements is used instead (so it allows us to tests library with different version of http-interop middleware).

Hope it's clearer now. If you have further questions just let me know :)

**Comment by harikt** [comment]
Thank you, it is very clear now. 

I didn't looked at the plugin dependency. Was only looking at source and thought that was a nice approach. Now I understand it.

Thank you for the detailed explanation.

**Comment by michalbundyra** [comment]
Closed in favour of #14

**Pull request closed without merging**
